# Generated by Django 4.0.3 on 2022-04-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('starttime', models.TimeField()),
                ('appointment_date', models.DateField()),
                ('endtime', models.TimeField()),
                ('appointment_type', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
                ('room_assigned', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment_Procedure',
            fields=[
                ('procedure_id', models.IntegerField(primary_key=True, serialize=False)),
                ('procedure_date', models.DateField()),
                ('invoice_id', models.IntegerField()),
                ('procedure_code', models.IntegerField()),
                ('procedure_type', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('tooth_involved', models.CharField(max_length=500)),
                ('amount_of_procedure', models.IntegerField()),
                ('patient_charge', models.FloatField()),
                ('insurance_charge', models.FloatField()),
                ('total_charge', models.FloatField()),
                ('bill_id', models.IntegerField()),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_claim',
            fields=[
                ('claim_id', models.IntegerField(primary_key=True, serialize=False)),
                ('claim_amount', models.FloatField()),
                ('insurance_company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('insurance', models.IntegerField()),
                ('health_card_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=50)),
                ('house_number', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('ssn', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=25)),
                ('email_address', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('treatment_type', models.CharField(max_length=20)),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('communication', models.CharField(max_length=500)),
                ('professionalism', models.CharField(max_length=500)),
                ('cleanliness', models.CharField(max_length=500)),
                ('value', models.IntegerField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_record',
            fields=[
                ('patient_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('medication', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=100)),
                ('tooth', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_billing',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_portion', models.FloatField()),
                ('insurance_portion', models.FloatField()),
                ('payment_type', models.CharField(max_length=50)),
                ('total_amount', models.FloatField()),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appointment')),
                ('insurance_claim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.insurance_claim')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_issue', models.DateField()),
                ('patient_charge', models.IntegerField()),
                ('insurance_charge', models.FloatField()),
                ('total_fee_charge', models.FloatField()),
                ('discount', models.FloatField()),
                ('penalty', models.FloatField()),
                ('insurance_claim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.insurance_claim')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Fee_Charge',
            fields=[
                ('feed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fee_code', models.IntegerField()),
                ('charge', models.IntegerField()),
                ('procedure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appointment_procedure')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_type', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
    ]
