# Generated by Django 4.0.3 on 2022-04-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_employee_id_appointment_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_record',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='appointment_type',
            new_name='appointment',
        ),
    ]
