# Generated by Django 4.0.3 on 2022-04-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_patient_id_patient_record_patient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='person',
        ),
    ]
