# Generated by Django 4.0.3 on 2022-04-11 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee_user_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='insurance_claim_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.insurance_claim'),
        ),
    ]
