# Generated by Django 4.0.4 on 2022-04-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_invoice_insurance_claim_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='insurance_claim_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.insurance_claim'),
        ),
    ]
