# Generated by Django 4.0.4 on 2022-04-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_invoice_insurance_claim_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comments',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='cleanliness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='professionalism',
            field=models.IntegerField(),
        ),
    ]
